clone:
  git:
    image: plugins/git
    remote: https://github.com/ylecuyer/test-drone.git
pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
      - ./.git
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/cache:/cache
  build:
    image: node:9.5
    commands:
      - npm install -g grunt-cli
      - git config --global user.email "test@testy.com"
      - git config --global user.name "Test testy"
      - git version
      - npm install
      - echo "coucou"
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
    - ./node_modules
    - ./.git
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/cache:/cache
